services:
  guidellm-bench:
    image: ghcr.io/vllm-project/guidellm:latest
    container_name: guidellm-bench

    environment:
      USER: guidellm
      LOGNAME: guidellm
      HOME: /tmp
    
    # volumes:
    #   - ./Qwen3.5/Autoround-L4-kv-fp8_e4m3-FLASHINFER-batched-8k-single:/results

    # volumes:
    #   - ./Qwen3.5/Autoround-L4-kv-fp8_e4m3-FLASHINFER-batched-8k-16req:/results
   
    command: >
      benchmark 
      --target "https://1knr0m2d6gijc9-8000.proxy.runpod.net/" 
      --model "Vishva007/Qwen3.5-9B-W4A16-AutoRound" 
      --request-type chat_completions
      --profile synchronous
      --max-requests 2
      --max-errors 2
      --data '{"kind": "huggingface", "source": "lmms-lab/MMBench_EN", "load_kwargs": {"split": "test"}, "prompt_tokens": 8000, "output_tokens": 2000}' 
      --data-column-mapper '{"image_column": "image", "text_column": "question"}' 
      --output-dir /results
      --outputs benchmark_single.json,benchmark_single.csv,benchmark_single.html

    # command: >
    #   benchmark 
    #   --target "https://1knr0m2d6gijc9-8000.proxy.runpod.net/" 
    #   --model "Vishva007/Qwen3.5-9B-W4A16-AutoRound" 
    #   --request-type chat_completions
    #   --profile concurrent
    #   --rate 16
    #   --max-requests 16
    #   --warmup 0.1
    #   --cooldown 0.1
    #   --max-errors 16
    #   --data '{"kind": "huggingface", "source": "lmms-lab/MMBench_EN", "load_kwargs": {"split": "test"}, "prompt_tokens": 8000, "output_tokens": 2000}' 
    #   --data-column-mapper '{"image_column": "image", "text_column": "question"}' 
    #   --output-dir /results
    #   --outputs benchmark_burst.json,benchmark_burst.csv,benchmark_burst.html